### ISSUE TITLE
Tunnel setup

### ISSUE THREAD

**Issue by lamiot** [bushev/SSHTunnel#2]
First is there a way to delete connections I previously set up and how?
Two can I change parameters for a session I previously set up and how?
Three can you walk me through the set up for a connection that would do the following:
Ssh -L  8081:localhost:80 uid@<myip>

**Comment by bushev** [comment]
Hi,

try to swipe a connection to the left, you will find action buttons (Edit/Delete/Disconnect).

To set up your connection, please configure:

Host: IP address of your SSH Server
Port: `22` (SSH Server port)

Port forwarding type: "`Local Port Forwarding`"
Destination host: `localhost`
Destination port: `80`

Bind Address: `127.0.0.1:8081`

**Comment by bushev** [comment]
Hmm, no. Deep tunneling is not supported. So you need to set up the second one manually.
