### ISSUE TITLE
Could not connect

### ISSUE THREAD

**Issue by kawssnoopy** [bushev/SSHTunnel#3]
I'm having trouble connecting with a private key.
The following is my screenshot:
https://gyazo.com/287545dc7c92b0039a793148ce7c2eea

**Comment by kawssnoopy** [comment]
I can connect to the ssh via computer.

**Comment by kawssnoopy** [comment]
I will try the docker open ssh server.

It looks like dynamic port forward should be able to connect, but I am trying to bind to a local port and get the error 'Unable to bind to a local port.
Port bind IP is set to: 127.0.0.1 and port to bind is set to: 5000.

**Comment by kawssnoopy** [comment]
Dynamic port worked!

**Comment by bushev** [comment]
That's fine. The application works well on your mobile device. Please, check **server logs**.
